Store\NewsBundle\Entity\Category:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }


Category:
  type: entity
  oneToMany:
    features:
      targetEntity: News
      mappedBy: category
News:
  type: entity
  manyToOne:
    category:
      targetEntity: Category
      inversedBy: news
      joinColumn:
        name: category_id
        referencedColumnName: id 
